using System;
using MessagePack;

namespace Bee.Api.Contracts.System
{
    /// <summary>
    /// Input arguments for the login operation.
    /// </summary>
    [MessagePackObject]
    [Serializable]
    public class LoginArgs : BusinessArgs
    {
        /// <summary>
        /// Gets or sets the user account identifier.
        /// </summary>
        [Key(100)]
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the password (plain text or pre-encrypted).
        /// </summary>
        [Key(101)]
        public string Password { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the RSA public key generated by the client for key exchange.
        /// </summary>
        [Key(102)]
        public string ClientPublicKey { get; set; } = string.Empty;
    }
}
