using System.ComponentModel;
using System.Globalization;
using Bee.Base.Data;
using Bee.Tests.Shared;
using Bee.Definition.Database;

namespace Bee.Db.UnitTests
{
    /// <summary>
    /// Oracle-specific integration tests: schema reader round-trip against the live fixture
    /// table, and session-level case-insensitive comparison provided by the connection-open
    /// hook (<c>ALTER SESSION SET NLS_COMP='LINGUISTIC' NLS_SORT='BINARY_CI'</c>). Skipped
    /// when no Oracle connection string is configured (<see cref="DbFactAttribute"/>
    /// handles the env-var check).
    /// </summary>
    [Collection("Initialize")]
    public class OracleIntegrationTests
    {
        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle SchemaProvider 應讀回 fixture 建好的 st_user 表")]
        public void SchemaProvider_ReadsFixtureTable()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var provider = new Bee.Db.Providers.Oracle.OracleTableSchemaProvider(databaseId);

            var schema = provider.GetTableSchema("st_user");

            Assert.NotNull(schema);
            Assert.Equal("st_user", schema!.TableName);
            // sys_no is NUMBER(19) GENERATED BY DEFAULT AS IDENTITY — read back as AutoIncrement.
            Assert.True(schema.Fields!.Contains("sys_no"));
            Assert.Equal(FieldDbType.AutoIncrement, schema.Fields["sys_no"].DbType);
            Assert.True(schema.Fields.Contains("sys_rowid"));
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle SchemaProvider 應對不存在的表回傳 null")]
        public void SchemaProvider_UnknownTable_ReturnsNull()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var provider = new Bee.Db.Providers.Oracle.OracleTableSchemaProvider(databaseId);

            var schema = provider.GetTableSchema("__no_such_table__");

            Assert.Null(schema);
        }

        [DbFact(DatabaseType.Oracle)]
        [DisplayName("Oracle 文字欄位字串比對應為 case-insensitive（session NLS_COMP=LINGUISTIC + NLS_SORT=BINARY_CI）")]
        public void StringComparison_IsCaseInsensitive()
        {
            var databaseId = TestDbConventions.GetDatabaseId(DatabaseType.Oracle);
            var dbAccess = new Bee.Db.DbAccess(databaseId);

            // 手寫 minimal DDL 以聚焦於驗證 Oracle 對 session-level NLS 的執行行為，
            // 與 OracleCreateTableCommandBuilder 純語法測試獨立。Oracle 無 DROP TABLE
            // IF EXISTS，改用 PL/SQL block + 吞 ORA-00942。
            string dropDdl =
                "BEGIN " +
                "  EXECUTE IMMEDIATE 'DROP TABLE \"ci_test\" CASCADE CONSTRAINTS'; " +
                "EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF; " +
                "END;";

            dbAccess.Execute(new Bee.Db.DbCommandSpec(Bee.Db.DbCommandKind.NonQuery, dropDdl));
            dbAccess.Execute(new Bee.Db.DbCommandSpec(Bee.Db.DbCommandKind.NonQuery,
                "CREATE TABLE \"ci_test\" (\"name\" VARCHAR2(50 CHAR) NOT NULL)"));

            try
            {
                dbAccess.Execute(new Bee.Db.DbCommandSpec(Bee.Db.DbCommandKind.NonQuery,
                    "INSERT INTO \"ci_test\" (\"name\") VALUES ({0})", "Jeff"));

                var result = dbAccess.Execute(new Bee.Db.DbCommandSpec(Bee.Db.DbCommandKind.Scalar,
                    "SELECT COUNT(*) FROM \"ci_test\" WHERE \"name\" = {0}", "jeff"));

                Assert.NotNull(result);
                Assert.Equal(1, Convert.ToInt32(result.Scalar!, CultureInfo.InvariantCulture));
            }
            finally
            {
                dbAccess.Execute(new Bee.Db.DbCommandSpec(Bee.Db.DbCommandKind.NonQuery, dropDdl));
            }
        }
    }
}
