using System.ComponentModel;
using Bee.Base.Data;
using Bee.Db.Providers.Oracle;
using Bee.Definition;
using Bee.Definition.Database;

namespace Bee.Db.UnitTests
{
    /// <summary>
    /// Pure-syntax tests for <see cref="OracleCreateTableCommandBuilder"/>. No live database
    /// connection — the builder produces string output that is asserted via
    /// <see cref="Assert.Contains(string, string)"/> against the well-known fragments
    /// for Oracle 19c+ dialect (double-quote quoting, NUMBER 系列、VARCHAR2(n CHAR)、
    /// GENERATED BY DEFAULT AS IDENTITY、independent COMMENT ON statements).
    /// </summary>
    public class OracleCreateTableCommandBuilderTests
    {
        private static TableSchema BuildSchema(FieldDbType dbType, int length = 0,
            int precision = 18, int scale = 0, bool allowNull = false, string defaultValue = "")
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            var field = schema.Fields.Add("col", "Col", dbType, length);
            field.Precision = precision;
            field.Scale = scale;
            field.AllowNull = allowNull;
            field.DefaultValue = defaultValue;
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);
            return schema;
        }

        #region GetOracleType 各 FieldDbType 分支

        [Theory]
        [InlineData(FieldDbType.Boolean, "NUMBER(1)")]
        [InlineData(FieldDbType.Short, "NUMBER(5)")]
        [InlineData(FieldDbType.Integer, "NUMBER(10)")]
        [InlineData(FieldDbType.Long, "NUMBER(19)")]
        [InlineData(FieldDbType.Currency, "NUMBER(19,4)")]
        [InlineData(FieldDbType.Date, "DATE")]
        [InlineData(FieldDbType.DateTime, "TIMESTAMP(6)")]
        [InlineData(FieldDbType.Guid, "RAW(16)")]
        [InlineData(FieldDbType.Binary, "BLOB")]
        [InlineData(FieldDbType.Text, "CLOB")]
        [DisplayName("GetCommandText 應為各 FieldDbType 產生對應的 Oracle 型別字串")]
        public void GetCommandText_FieldDbType_GeneratesCorrectColumnType(FieldDbType dbType, string expectedFragment)
        {
            var schema = BuildSchema(dbType);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains(expectedFragment, sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 型別應使用 VARCHAR2(n CHAR) 並指定字元長度")]
        public void GetCommandText_String_UsesVarchar2CharSemantics()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // CHAR semantic 避免中文/多 byte 字元被截斷
            Assert.Contains("VARCHAR2(50 CHAR)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 長度超過 4000 byte 上限應改用 CLOB")]
        public void GetCommandText_StringOverVarcharLimit_FallsBackToClob()
        {
            var schema = BuildSchema(FieldDbType.String, length: 8000);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // VARCHAR2 標準上限 4000 byte；超過時退化為 CLOB 而非依賴 EXTENDED 模式
            Assert.Contains("\"col\" CLOB", sql);
            Assert.DoesNotContain("VARCHAR2", sql);
        }

        [Fact]
        [DisplayName("GetCommandText String 長度為 0 應改用 CLOB")]
        public void GetCommandText_StringZeroLength_FallsBackToClob()
        {
            var schema = BuildSchema(FieldDbType.String, length: 0);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" CLOB", sql);
        }

        [Fact]
        [DisplayName("GetCommandText Decimal 應使用 NUMBER(precision,scale)")]
        public void GetCommandText_Decimal_UsesNumberPrecisionScale()
        {
            var schema = BuildSchema(FieldDbType.Decimal, precision: 12, scale: 3);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("NUMBER(12,3)", sql);
        }

        [Fact]
        [DisplayName("GetCommandText 不支援的 FieldDbType 應擲出 InvalidOperationException")]
        public void GetCommandText_UnknownDbType_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("col", "Col", (FieldDbType)999);
            var builder = new OracleCreateTableCommandBuilder();

            Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
        }

        #endregion

        #region 識別符引用與表後綴

        [Fact]
        [DisplayName("識別符應以雙引號引用（Oracle reserved word 多，statically quote 為安全策略）")]
        public void GetCommandText_Identifiers_UseDoubleQuotes()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE TABLE \"st_demo\"", sql);
            Assert.Contains("\"col\"", sql);
        }

        [Fact]
        [DisplayName("CREATE TABLE 不應帶 ENGINE / CHARSET / COLLATE 後綴（Oracle 走 DB 預設）")]
        public void GetCommandText_NoTableSuffix()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle 採 session 級 NLS 設定（GlobalFixture ALTER SESSION）取代 column-level COLLATE
            Assert.DoesNotContain("ENGINE=", sql);
            Assert.DoesNotContain("CHARSET=", sql);
            Assert.DoesNotContain("COLLATE", sql);
        }

        [Fact]
        [DisplayName("含特殊字元（雙引號）的識別符應正確 escape")]
        public void GetCommandText_IdentifierWithDoubleQuote_IsEscaped()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields.Add("col\"x", "Col", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\"\"x\"", sql);
        }

        #endregion

        #region Default Expressions

        [Fact]
        [DisplayName("非 AllowNull Integer 欄位應產生 DEFAULT 0 NOT NULL（Oracle 順序為 type DEFAULT NOT NULL）")]
        public void GetCommandText_NonNullInteger_GeneratesDefault0NotNull()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" NUMBER(10) DEFAULT 0 NOT NULL", sql);
        }

        [Fact]
        [DisplayName("非 AllowNull String 欄位應產生空字串 DEFAULT")]
        public void GetCommandText_NonNullString_GeneratesEmptyStringDefault()
        {
            var schema = BuildSchema(FieldDbType.String, length: 50, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT '' NOT NULL", sql);
        }

        [Fact]
        [DisplayName("AllowNull 欄位不應有 DEFAULT 子句")]
        public void GetCommandText_AllowNullField_OmitsDefault()
        {
            var schema = BuildSchema(FieldDbType.Integer, allowNull: true);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"col\" NUMBER(10) NULL", sql);
            Assert.DoesNotContain("\"col\" NUMBER(10) DEFAULT", sql);
        }

        [Fact]
        [DisplayName("Guid 欄位 DEFAULT 應為 SYS_GUID()")]
        public void GetCommandText_NonNullGuid_GeneratesSysGuidDefault()
        {
            var schema = BuildSchema(FieldDbType.Guid, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT SYS_GUID()", sql);
        }

        [Fact]
        [DisplayName("DateTime 欄位 DEFAULT 應為 SYSTIMESTAMP")]
        public void GetCommandText_NonNullDateTime_GeneratesSystimestampDefault()
        {
            var schema = BuildSchema(FieldDbType.DateTime, allowNull: false);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT SYSTIMESTAMP", sql);
        }

        [Fact]
        [DisplayName("Text/Binary 欄位即使 NOT NULL 也不應產生 DEFAULT（CLOB/BLOB 限制）")]
        public void GetCommandText_TextBinary_OmitsDefault()
        {
            var textSchema = new TableSchema { TableName = "st_demo" };
            textSchema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            textSchema.Fields.Add("note", "Note", FieldDbType.Text);
            textSchema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(textSchema);

            Assert.Contains("\"note\" CLOB NOT NULL", sql);
            Assert.DoesNotContain("\"note\" CLOB DEFAULT", sql);
        }

        [Fact]
        [DisplayName("含單引號的 String DEFAULT 值應 escape 成雙單引號")]
        public void GetCommandText_StringDefaultWithQuote_IsEscaped()
        {
            var schema = BuildSchema(FieldDbType.String, length: 20, defaultValue: "O'Brien");
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("DEFAULT 'O''Brien'", sql);
        }

        #endregion

        #region AutoIncrement

        [Fact]
        [DisplayName("AutoIncrement 欄位應產生 NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL")]
        public void GetCommandText_AutoIncrement_UsesIdentitySyntax()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            schema.Indexes!.AddPrimaryKey("sys_no");
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"sys_no\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            // Oracle 不允許 inline column-level PRIMARY KEY，必為 table-level CONSTRAINT
            Assert.Contains("CONSTRAINT", sql);
            Assert.Contains("PRIMARY KEY (\"sys_no\")", sql);
        }

        [Fact]
        [DisplayName("AutoIncrement 欄位若非單欄 PK 應拋 InvalidOperationException")]
        public void GetCommandText_AutoIncrementNotSinglePk_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            schema.Fields!.Add("other", "Other", FieldDbType.String, 10);
            schema.Indexes!.AddPrimaryKey("other");

            var builder = new OracleCreateTableCommandBuilder();
            var ex = Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
            Assert.Contains("must be the single-column primary key", ex.Message);
        }

        [Fact]
        [DisplayName("無宣告 PK 但有 AutoIncrement 欄位應自動以 pk_{表名} 為 PK constraint name")]
        public void GetCommandText_AutoIncrementWithoutDeclaredPk_UsesDefaultPkName()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add("sys_no", "No", FieldDbType.AutoIncrement);
            // 不在 Indexes 加 PK；由 builder 自動產生 PK constraint
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("\"sys_no\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL", sql);
            Assert.Contains("CONSTRAINT \"pk_st_demo\" PRIMARY KEY (\"sys_no\")", sql);
        }

        [Fact]
        [DisplayName("多個 AutoIncrement 欄位應拋 InvalidOperationException")]
        public void GetCommandText_MultipleAutoIncrement_Throws()
        {
            var schema = new TableSchema { TableName = "st_bad" };
            schema.Fields!.Add("a", "A", FieldDbType.AutoIncrement);
            schema.Fields!.Add("b", "B", FieldDbType.AutoIncrement);
            schema.Indexes!.AddPrimaryKey("a");

            var builder = new OracleCreateTableCommandBuilder();
            var ex = Assert.Throws<InvalidOperationException>(() => builder.GetCommandText(schema));
            Assert.Contains("at most one IDENTITY", ex.Message);
        }

        #endregion

        #region PRIMARY KEY 與索引

        [Fact]
        [DisplayName("無 AutoIncrement 的 schema 應產生獨立 PRIMARY KEY constraint")]
        public void GetCommandText_NonAutoIncrementSchema_EmitsPrimaryKeyConstraint()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.Contains("CONSTRAINT \"pk_st_demo\" PRIMARY KEY (\"sys_rowid\")", sql);
        }

        [Fact]
        [DisplayName("PK constraint 不應帶 ASC/DESC 排序方向（Oracle 語法限制）")]
        public void GetCommandText_PrimaryKey_OmitsSortDirection()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            // Oracle 的 PRIMARY KEY constraint 內 column 不接受 ASC/DESC
            Assert.DoesNotContain("PRIMARY KEY (\"sys_rowid\" ASC)", sql);
            Assert.DoesNotContain("PRIMARY KEY (\"sys_rowid\" DESC)", sql);
        }

        [Fact]
        [DisplayName("非 PK 索引應產生 CREATE INDEX 語句並帶 ASC/DESC")]
        public void GetCommandText_NonPkIndexes_EmitCreateIndexStatements()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.Indexes!.Add("ix_{0}_col", "col", false);
            schema.Indexes!.Add("uk_{0}_col", "col", true);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("CREATE INDEX \"ix_st_demo_col\" ON \"st_demo\" (\"col\" ASC);", sql);
            Assert.Contains("CREATE UNIQUE INDEX \"uk_st_demo_col\" ON \"st_demo\" (\"col\" ASC);", sql);
        }

        #endregion

        #region COMMENT ON

        [Fact]
        [DisplayName("DisplayName 非空時應產生獨立 COMMENT ON TABLE 語句")]
        public void GetCommandText_DisplayName_EmitsCommentOnTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            schema.DisplayName = "示範資料表";

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON TABLE \"st_demo\" IS '示範資料表';", sql);
        }

        [Fact]
        [DisplayName("DisplayName 為空時不應產生 COMMENT ON TABLE 語句")]
        public void GetCommandText_NoDisplayName_OmitsCommentOnTable()
        {
            var schema = BuildSchema(FieldDbType.Integer);
            var builder = new OracleCreateTableCommandBuilder();

            string sql = builder.GetCommandText(schema);

            Assert.DoesNotContain("COMMENT ON TABLE", sql);
        }

        [Fact]
        [DisplayName("Caption 非空的欄位應產生對應 COMMENT ON COLUMN 語句")]
        public void GetCommandText_FieldCaption_EmitsCommentOnColumn()
        {
            var schema = BuildSchema(FieldDbType.Integer);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"sys_rowid\" IS 'Row ID';", sql);
            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"col\" IS 'Col';", sql);
        }

        [Fact]
        [DisplayName("Caption 含單引號應 escape 成雙單引號")]
        public void GetCommandText_CaptionWithQuote_IsEscaped()
        {
            var schema = new TableSchema { TableName = "st_demo" };
            schema.Fields!.Add(SysFields.RowId, "Row ID", FieldDbType.Guid);
            schema.Fields.Add("col", "User's note", FieldDbType.Integer);
            schema.Indexes!.AddPrimaryKey(SysFields.RowId);

            var builder = new OracleCreateTableCommandBuilder();
            string sql = builder.GetCommandText(schema);

            Assert.Contains("COMMENT ON COLUMN \"st_demo\".\"col\" IS 'User''s note';", sql);
        }

        #endregion
    }
}
