using System.ComponentModel;
using Bee.Base.Data;
using Bee.Db.Providers.PostgreSql;
using Bee.Definition.Database;

namespace Bee.Db.UnitTests
{
    public class PgSchemaMappingTests
    {
        private static DbField MakeField(FieldDbType dbType, int length = 0,
            int precision = 18, int scale = 0, bool allowNull = false, string defaultValue = "")
        {
            return new DbField("col", "Col", dbType)
            {
                Length = length,
                Precision = precision,
                Scale = scale,
                AllowNull = allowNull,
                DefaultValue = defaultValue
            };
        }

        #region PgTypeMapping.GetPgType

        [Theory]
        [InlineData(FieldDbType.Text, "text")]
        [InlineData(FieldDbType.Boolean, "boolean")]
        [InlineData(FieldDbType.AutoIncrement, "integer GENERATED BY DEFAULT AS IDENTITY")]
        [InlineData(FieldDbType.Short, "smallint")]
        [InlineData(FieldDbType.Integer, "integer")]
        [InlineData(FieldDbType.Long, "bigint")]
        [InlineData(FieldDbType.Currency, "numeric(19,4)")]
        [InlineData(FieldDbType.Date, "date")]
        [InlineData(FieldDbType.DateTime, "timestamp")]
        [InlineData(FieldDbType.Guid, "uuid")]
        [InlineData(FieldDbType.Binary, "bytea")]
        [DisplayName("GetPgType 應正確映射各 FieldDbType 至 PostgreSQL 型別")]
        public void GetPgType_VariousTypes_MapsCorrectly(FieldDbType dbType, string expected)
        {
            var field = MakeField(dbType);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal(expected, result);
        }

        [Fact]
        [DisplayName("GetPgType String 應回傳 varchar(n)")]
        public void GetPgType_String_ReturnsVarchar()
        {
            var field = MakeField(FieldDbType.String, length: 50);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal("varchar(50)", result);
        }

        [Fact]
        [DisplayName("GetPgType Decimal precision/scale 為 0 時應使用預設 numeric(18,0)")]
        public void GetPgType_Decimal_ZeroPrecisionScale_UsesDefaults()
        {
            var field = MakeField(FieldDbType.Decimal, precision: 0, scale: 0);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal("numeric(18,0)", result);
        }

        [Fact]
        [DisplayName("GetPgType Decimal 應使用指定的 precision/scale")]
        public void GetPgType_Decimal_UsesSpecifiedPrecisionScale()
        {
            var field = MakeField(FieldDbType.Decimal, precision: 12, scale: 3);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal("numeric(12,3)", result);
        }

        [Fact]
        [DisplayName("GetPgType 不支援的 FieldDbType 應擲出 InvalidOperationException")]
        public void GetPgType_UnknownDbType_ThrowsInvalidOperation()
        {
            var field = MakeField(FieldDbType.Unknown);
            Assert.Throws<InvalidOperationException>(() => PgTypeMapping.GetPgType(field));
        }

        #endregion

        #region PgSchemaHelper.QuoteName

        [Fact]
        [DisplayName("QuoteName 普通識別碼應以雙引號包裹")]
        public void QuoteName_SimpleIdentifier_WrapsInDoubleQuotes()
        {
            var result = PgSchemaHelper.QuoteName("col_name");
            Assert.Equal("\"col_name\"", result);
        }

        [Fact]
        [DisplayName("QuoteName 識別碼含雙引號時應跳脫為兩個雙引號")]
        public void QuoteName_IdentifierWithDoubleQuote_EscapesDoubleQuotes()
        {
            var result = PgSchemaHelper.QuoteName("col\"name");
            Assert.Equal("\"col\"\"name\"", result);
        }

        #endregion

        #region PgSchemaHelper.EscapeSqlString

        [Fact]
        [DisplayName("EscapeSqlString 無單引號時應原樣回傳")]
        public void EscapeSqlString_NoSingleQuotes_ReturnsUnchanged()
        {
            var result = PgSchemaHelper.EscapeSqlString("hello world");
            Assert.Equal("hello world", result);
        }

        [Fact]
        [DisplayName("EscapeSqlString 含單引號時應跳脫為兩個單引號")]
        public void EscapeSqlString_WithSingleQuotes_EscapesCorrectly()
        {
            var result = PgSchemaHelper.EscapeSqlString("it's a test");
            Assert.Equal("it''s a test", result);
        }

        #endregion

        #region PgSchemaHelper.GetDefaultValueExpression

        [Theory]
        [InlineData(FieldDbType.String, "")]
        [InlineData(FieldDbType.Text, "")]
        [InlineData(FieldDbType.Boolean, "0")]
        [InlineData(FieldDbType.Short, "0")]
        [InlineData(FieldDbType.Integer, "0")]
        [InlineData(FieldDbType.Long, "0")]
        [InlineData(FieldDbType.Decimal, "0")]
        [InlineData(FieldDbType.Currency, "0")]
        [InlineData(FieldDbType.Date, "CURRENT_TIMESTAMP")]
        [InlineData(FieldDbType.DateTime, "CURRENT_TIMESTAMP")]
        [InlineData(FieldDbType.Guid, "gen_random_uuid()")]
        [DisplayName("GetDefaultValueExpression 應回傳各型別的內建 PostgreSQL 預設值")]
        public void GetDefaultValueExpression_VariousTypes_ReturnsExpected(FieldDbType dbType, string expected)
        {
            var result = PgSchemaHelper.GetDefaultValueExpression(dbType);
            Assert.Equal(expected, result);
        }

        [Fact]
        [DisplayName("GetDefaultValueExpression 未對應型別應回傳空字串")]
        public void GetDefaultValueExpression_UnknownType_ReturnsEmpty()
        {
            var result = PgSchemaHelper.GetDefaultValueExpression(FieldDbType.Unknown);
            Assert.Equal(string.Empty, result);
        }

        #endregion

        #region PgSchemaHelper.GetDefaultExpression

        [Fact]
        [DisplayName("GetDefaultExpression AllowNull 欄位應回傳空字串")]
        public void GetDefaultExpression_AllowNull_ReturnsEmpty()
        {
            var field = MakeField(FieldDbType.Integer, allowNull: true);
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal(string.Empty, result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression AutoIncrement 欄位應回傳空字串")]
        public void GetDefaultExpression_AutoIncrement_ReturnsEmpty()
        {
            var field = MakeField(FieldDbType.AutoIncrement, allowNull: false);
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal(string.Empty, result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression String 空 DefaultValue 應回傳 ''")]
        public void GetDefaultExpression_StringEmptyDefault_ReturnsEmptyLiteral()
        {
            var field = MakeField(FieldDbType.String, allowNull: false, defaultValue: "");
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal("''", result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression String 自訂 DefaultValue 含單引號時應跳脫並包裹")]
        public void GetDefaultExpression_StringCustomDefaultWithQuote_EscapesAndWraps()
        {
            var field = MakeField(FieldDbType.String, allowNull: false, defaultValue: "it's");
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal("'it''s'", result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression String 自訂 DefaultValue 無特殊字元時應包裹")]
        public void GetDefaultExpression_StringCustomDefault_WrapsInSingleQuotes()
        {
            var field = MakeField(FieldDbType.String, allowNull: false, defaultValue: "hello");
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal("'hello'", result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression Integer 空 DefaultValue 應回傳 0")]
        public void GetDefaultExpression_IntegerEmptyDefault_ReturnsZero()
        {
            var field = MakeField(FieldDbType.Integer, allowNull: false, defaultValue: "");
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal("0", result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression Integer 自訂 DefaultValue 應使用自訂值")]
        public void GetDefaultExpression_IntegerCustomDefault_ReturnsCustomValue()
        {
            var field = MakeField(FieldDbType.Integer, allowNull: false, defaultValue: "99");
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal("99", result);
        }

        [Fact]
        [DisplayName("GetDefaultExpression DateTime 欄位應回傳 CURRENT_TIMESTAMP")]
        public void GetDefaultExpression_DateTime_ReturnsCurrentTimestamp()
        {
            var field = MakeField(FieldDbType.DateTime, allowNull: false);
            var result = PgSchemaHelper.GetDefaultExpression(field);
            Assert.Equal("CURRENT_TIMESTAMP", result);
        }

        #endregion

        #region PgSchemaHelper.GetColumnDefinition

        [Fact]
        [DisplayName("GetColumnDefinition NOT NULL Integer 應包含型別、NULL 標記與 DEFAULT")]
        public void GetColumnDefinition_NotNullInteger_GeneratesFullDefinition()
        {
            var field = MakeField(FieldDbType.Integer, allowNull: false);
            var result = PgSchemaHelper.GetColumnDefinition(field);
            Assert.Equal("\"col\" integer NOT NULL DEFAULT 0", result);
        }

        [Fact]
        [DisplayName("GetColumnDefinition NULL 欄位應不包含 DEFAULT 子句")]
        public void GetColumnDefinition_NullableField_NoDefaultClause()
        {
            var field = MakeField(FieldDbType.Integer, allowNull: true);
            var result = PgSchemaHelper.GetColumnDefinition(field);
            Assert.Equal("\"col\" integer NULL", result);
        }

        [Fact]
        [DisplayName("GetColumnDefinition Guid NOT NULL 應使用 gen_random_uuid()")]
        public void GetColumnDefinition_NotNullGuid_UsesGenRandomUuid()
        {
            var field = MakeField(FieldDbType.Guid, allowNull: false);
            var result = PgSchemaHelper.GetColumnDefinition(field);
            Assert.Equal("\"col\" uuid NOT NULL DEFAULT gen_random_uuid()", result);
        }

        #endregion
    }
}
