using System.ComponentModel;
using Bee.Base.Data;
using Bee.Db.Providers.PostgreSql;
using Bee.Definition.Database;

namespace Bee.Db.UnitTests
{
    public class PgTypeMappingTests
    {
        private static DbField MakeField(FieldDbType dbType, int length = 0, int precision = 0, int scale = 0)
        {
            var field = new DbField("col", "Col", dbType);
            field.Length = length;
            field.Precision = precision;
            field.Scale = scale;
            return field;
        }

        [Theory]
        [InlineData(FieldDbType.String, 50, 0, 0, "varchar(50)")]
        [InlineData(FieldDbType.Text, 0, 0, 0, "text")]
        [InlineData(FieldDbType.Boolean, 0, 0, 0, "boolean")]
        [InlineData(FieldDbType.AutoIncrement, 0, 0, 0, "integer GENERATED BY DEFAULT AS IDENTITY")]
        [InlineData(FieldDbType.Short, 0, 0, 0, "smallint")]
        [InlineData(FieldDbType.Integer, 0, 0, 0, "integer")]
        [InlineData(FieldDbType.Long, 0, 0, 0, "bigint")]
        [InlineData(FieldDbType.Currency, 0, 0, 0, "numeric(19,4)")]
        [InlineData(FieldDbType.Date, 0, 0, 0, "date")]
        [InlineData(FieldDbType.DateTime, 0, 0, 0, "timestamp")]
        [InlineData(FieldDbType.Guid, 0, 0, 0, "uuid")]
        [InlineData(FieldDbType.Binary, 0, 0, 0, "bytea")]
        [DisplayName("GetPgType 應為各 FieldDbType 回傳正確的 PostgreSQL 型別字串")]
        public void GetPgType_VariousDbTypes_ReturnsCorrectPgType(
            FieldDbType dbType, int length, int precision, int scale, string expected)
        {
            var field = MakeField(dbType, length, precision, scale);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal(expected, result);
        }

        [Fact]
        [DisplayName("GetPgType Decimal 應使用指定的 Precision/Scale")]
        public void GetPgType_Decimal_UsesPrecisionAndScale()
        {
            var field = MakeField(FieldDbType.Decimal, precision: 12, scale: 3);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal("numeric(12,3)", result);
        }

        [Fact]
        [DisplayName("GetPgType Decimal Precision/Scale 為 0 時應套用預設值 18/0")]
        public void GetPgType_Decimal_ZeroPrecision_UsesDefault()
        {
            var field = MakeField(FieldDbType.Decimal, precision: 0, scale: 0);
            var result = PgTypeMapping.GetPgType(field);
            Assert.Equal("numeric(18,0)", result);
        }

        [Fact]
        [DisplayName("GetPgType 不支援的 FieldDbType 應擲出 InvalidOperationException")]
        public void GetPgType_UnknownDbType_ThrowsInvalidOperationException()
        {
            var field = MakeField(FieldDbType.Unknown);
            Assert.Throws<InvalidOperationException>(() => PgTypeMapping.GetPgType(field));
        }
    }
}
