// Generated from the Bee.NET message types — do not edit by hand.
//
// An encoded payload must name its type in the envelope; the server resolves it from this
// string and screens it against an allow-list first.

export const WireTypeNames = {
  ApiCallContext: 'Bee.Api.Core.Messages.ApiCallContext, Bee.Api.Core',
  CheckPackageUpdateRequest: 'Bee.Api.Core.Messages.System.CheckPackageUpdateRequest, Bee.Api.Core',
  CheckPackageUpdateResponse: 'Bee.Api.Core.Messages.System.CheckPackageUpdateResponse, Bee.Api.Core',
  CreateApiKeyRequest: 'Bee.Api.Core.Messages.System.CreateApiKeyRequest, Bee.Api.Core',
  CreateApiKeyResponse: 'Bee.Api.Core.Messages.System.CreateApiKeyResponse, Bee.Api.Core',
  CreateSessionRequest: 'Bee.Api.Core.Messages.System.CreateSessionRequest, Bee.Api.Core',
  CreateSessionResponse: 'Bee.Api.Core.Messages.System.CreateSessionResponse, Bee.Api.Core',
  DeleteRequest: 'Bee.Api.Core.Messages.Form.DeleteRequest, Bee.Api.Core',
  DeleteResponse: 'Bee.Api.Core.Messages.Form.DeleteResponse, Bee.Api.Core',
  EnterCompanyRequest: 'Bee.Api.Core.Messages.System.EnterCompanyRequest, Bee.Api.Core',
  EnterCompanyResponse: 'Bee.Api.Core.Messages.System.EnterCompanyResponse, Bee.Api.Core',
  ExecFuncRequest: 'Bee.Api.Core.Messages.ExecFuncRequest, Bee.Api.Core',
  ExecFuncResponse: 'Bee.Api.Core.Messages.ExecFuncResponse, Bee.Api.Core',
  GetAccessLogRequest: 'Bee.Api.Core.Messages.AuditLog.GetAccessLogRequest, Bee.Api.Core',
  GetApiAnomalyLogRequest: 'Bee.Api.Core.Messages.AuditLog.GetApiAnomalyLogRequest, Bee.Api.Core',
  GetApiAnomalySummaryRequest: 'Bee.Api.Core.Messages.AuditLog.GetApiAnomalySummaryRequest, Bee.Api.Core',
  GetChangeDetailRequest: 'Bee.Api.Core.Messages.AuditLog.GetChangeDetailRequest, Bee.Api.Core',
  GetChangeDetailResponse: 'Bee.Api.Core.Messages.AuditLog.GetChangeDetailResponse, Bee.Api.Core',
  GetChangeLogRequest: 'Bee.Api.Core.Messages.AuditLog.GetChangeLogRequest, Bee.Api.Core',
  GetCommonConfigurationRequest: 'Bee.Api.Core.Messages.System.GetCommonConfigurationRequest, Bee.Api.Core',
  GetCommonConfigurationResponse: 'Bee.Api.Core.Messages.System.GetCommonConfigurationResponse, Bee.Api.Core',
  GetCustomizePluginSettingsRequest: 'Bee.Api.Core.Messages.System.GetCustomizePluginSettingsRequest, Bee.Api.Core',
  GetCustomizePluginSettingsResponse: 'Bee.Api.Core.Messages.System.GetCustomizePluginSettingsResponse, Bee.Api.Core',
  GetDataRequest: 'Bee.Api.Core.Messages.Form.GetDataRequest, Bee.Api.Core',
  GetDataResponse: 'Bee.Api.Core.Messages.Form.GetDataResponse, Bee.Api.Core',
  GetDbAnomalyLogRequest: 'Bee.Api.Core.Messages.AuditLog.GetDbAnomalyLogRequest, Bee.Api.Core',
  GetDbAnomalySummaryRequest: 'Bee.Api.Core.Messages.AuditLog.GetDbAnomalySummaryRequest, Bee.Api.Core',
  GetDefineRequest: 'Bee.Api.Core.Messages.System.GetDefineRequest, Bee.Api.Core',
  GetDefineResponse: 'Bee.Api.Core.Messages.System.GetDefineResponse, Bee.Api.Core',
  GetDepartmentTreeRequest: 'Bee.Api.Core.Messages.System.GetDepartmentTreeRequest, Bee.Api.Core',
  GetDepartmentTreeResponse: 'Bee.Api.Core.Messages.System.GetDepartmentTreeResponse, Bee.Api.Core',
  GetFormLayoutRequest: 'Bee.Api.Core.Messages.System.GetFormLayoutRequest, Bee.Api.Core',
  GetFormLayoutResponse: 'Bee.Api.Core.Messages.System.GetFormLayoutResponse, Bee.Api.Core',
  GetFormSchemaRequest: 'Bee.Api.Core.Messages.System.GetFormSchemaRequest, Bee.Api.Core',
  GetFormSchemaResponse: 'Bee.Api.Core.Messages.System.GetFormSchemaResponse, Bee.Api.Core',
  GetLanguageRequest: 'Bee.Api.Core.Messages.System.GetLanguageRequest, Bee.Api.Core',
  GetLanguageResponse: 'Bee.Api.Core.Messages.System.GetLanguageResponse, Bee.Api.Core',
  GetListRequest: 'Bee.Api.Core.Messages.Form.GetListRequest, Bee.Api.Core',
  GetListResponse: 'Bee.Api.Core.Messages.Form.GetListResponse, Bee.Api.Core',
  GetLoginLogRequest: 'Bee.Api.Core.Messages.AuditLog.GetLoginLogRequest, Bee.Api.Core',
  GetLookupRequest: 'Bee.Api.Core.Messages.Form.GetLookupRequest, Bee.Api.Core',
  GetLookupResponse: 'Bee.Api.Core.Messages.Form.GetLookupResponse, Bee.Api.Core',
  GetNewDataRequest: 'Bee.Api.Core.Messages.Form.GetNewDataRequest, Bee.Api.Core',
  GetNewDataResponse: 'Bee.Api.Core.Messages.Form.GetNewDataResponse, Bee.Api.Core',
  GetPackageRequest: 'Bee.Api.Core.Messages.System.GetPackageRequest, Bee.Api.Core',
  GetPackageResponse: 'Bee.Api.Core.Messages.System.GetPackageResponse, Bee.Api.Core',
  GetTopApiMethodsRequest: 'Bee.Api.Core.Messages.AuditLog.GetTopApiMethodsRequest, Bee.Api.Core',
  LeaveCompanyRequest: 'Bee.Api.Core.Messages.System.LeaveCompanyRequest, Bee.Api.Core',
  LeaveCompanyResponse: 'Bee.Api.Core.Messages.System.LeaveCompanyResponse, Bee.Api.Core',
  ListApiKeysRequest: 'Bee.Api.Core.Messages.System.ListApiKeysRequest, Bee.Api.Core',
  ListApiKeysResponse: 'Bee.Api.Core.Messages.System.ListApiKeysResponse, Bee.Api.Core',
  LogAggregateResponse: 'Bee.Api.Core.Messages.AuditLog.LogAggregateResponse, Bee.Api.Core',
  LogListResponse: 'Bee.Api.Core.Messages.AuditLog.LogListResponse, Bee.Api.Core',
  LoginRequest: 'Bee.Api.Core.Messages.System.LoginRequest, Bee.Api.Core',
  LoginResponse: 'Bee.Api.Core.Messages.System.LoginResponse, Bee.Api.Core',
  LogoutRequest: 'Bee.Api.Core.Messages.System.LogoutRequest, Bee.Api.Core',
  LogoutResponse: 'Bee.Api.Core.Messages.System.LogoutResponse, Bee.Api.Core',
  PingRequest: 'Bee.Api.Core.Messages.System.PingRequest, Bee.Api.Core',
  PingResponse: 'Bee.Api.Core.Messages.System.PingResponse, Bee.Api.Core',
  SaveCustomizePluginSettingsRequest: 'Bee.Api.Core.Messages.System.SaveCustomizePluginSettingsRequest, Bee.Api.Core',
  SaveCustomizePluginSettingsResponse: 'Bee.Api.Core.Messages.System.SaveCustomizePluginSettingsResponse, Bee.Api.Core',
  SaveDefineRequest: 'Bee.Api.Core.Messages.System.SaveDefineRequest, Bee.Api.Core',
  SaveDefineResponse: 'Bee.Api.Core.Messages.System.SaveDefineResponse, Bee.Api.Core',
  SaveRequest: 'Bee.Api.Core.Messages.Form.SaveRequest, Bee.Api.Core',
  SaveResponse: 'Bee.Api.Core.Messages.Form.SaveResponse, Bee.Api.Core',
  SetApiKeyEnabledRequest: 'Bee.Api.Core.Messages.System.SetApiKeyEnabledRequest, Bee.Api.Core',
  SetApiKeyEnabledResponse: 'Bee.Api.Core.Messages.System.SetApiKeyEnabledResponse, Bee.Api.Core',
  SetApiKeyExpiryRequest: 'Bee.Api.Core.Messages.System.SetApiKeyExpiryRequest, Bee.Api.Core',
  SetApiKeyExpiryResponse: 'Bee.Api.Core.Messages.System.SetApiKeyExpiryResponse, Bee.Api.Core',
  SetDeploymentAdminRequest: 'Bee.Api.Core.Messages.System.SetDeploymentAdminRequest, Bee.Api.Core',
  SetDeploymentAdminResponse: 'Bee.Api.Core.Messages.System.SetDeploymentAdminResponse, Bee.Api.Core',
} as const;

export type WireTypeName = keyof typeof WireTypeNames;
