using System.Globalization;
using System.Text;
using Bee.Base;
using Bee.Base.Data;
using Bee.Db.Ddl;
using Bee.Definition.Database;

namespace Bee.Db.Providers.Oracle
{
    /// <summary>
    /// Generates CREATE TABLE SQL statements for Oracle 19c+. Counterpart to
    /// <see cref="MySql.MySqlCreateTableCommandBuilder"/> and
    /// <see cref="Sqlite.SqliteCreateTableCommandBuilder"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Dialect-specific output (see docs/plans/plan-oracle-support.md):
    /// </para>
    /// <list type="bullet">
    /// <item>Double-quoted identifiers; FormSchema convention is lowercase to side-step the
    ///       case-sensitivity that quoted identifiers introduce on Oracle.</item>
    /// <item><c>NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL</c> for AutoIncrement
    ///       columns. Oracle does not support an inline column-level PRIMARY KEY clause,
    ///       so the PK is always emitted as a table-level <c>CONSTRAINT ... PRIMARY KEY</c>
    ///       (unlike MySQL/SQLite which inline it on the AutoIncrement column line).</item>
    ///  <item>Captions are not emitted inline: Oracle stores table/column captions in
    ///       <c>ALL_TAB_COMMENTS</c> / <c>ALL_COL_COMMENTS</c>, populated by trailing
    ///       <c>COMMENT ON TABLE</c> / <c>COMMENT ON COLUMN</c> statements after the table
    ///       is created.</item>
    /// <item>Case-insensitive comparison is set per-session by the connection initializer
    ///       (<c>ALTER SESSION SET NLS_COMP='LINGUISTIC' NLS_SORT='BINARY_CI'</c>), not via
    ///       column-level COLLATE — so the CREATE TABLE output stays free of per-column
    ///       collation clauses.</item>
    /// </list>
    /// </remarks>
    public class OracleCreateTableCommandBuilder : ICreateTableCommandBuilder
    {
        private TableSchema? _dbTable;

        /// <summary>
        /// Initializes a new instance of <see cref="OracleCreateTableCommandBuilder"/>.
        /// </summary>
        public OracleCreateTableCommandBuilder()
        { }

        /// <summary>
        /// Gets the table schema definition.
        /// </summary>
        private TableSchema TableSchema => _dbTable!;

        /// <summary>
        /// Gets the SQL statement for creating a table.
        /// </summary>
        /// <param name="tableSchema">The table schema definition.</param>
        public string GetCommandText(TableSchema tableSchema)
        {
            _dbTable = tableSchema;
            ValidateAutoIncrement();
            return $"-- Create table {this.TableSchema.TableName}\r\n{this.GetCreateTableCommandText()}";
        }

        /// <summary>
        /// Gets the AutoIncrement field if the schema contains exactly one; null otherwise.
        /// Throws when multiple AutoIncrement fields are present (Oracle allows at most one
        /// IDENTITY column per table).
        /// </summary>
        private DbField? GetAutoIncrementField()
        {
            var autoIncrementFields = this.TableSchema.Fields!
                .Where(f => f.DbType == FieldDbType.AutoIncrement)
                .ToList();

            if (autoIncrementFields.Count == 0) return null;
            if (autoIncrementFields.Count > 1)
                throw new InvalidOperationException(
                    $"On Oracle, table '{TableSchema.TableName}' declares {autoIncrementFields.Count} AutoIncrement fields. "
                    + "Oracle supports at most one IDENTITY column per table.");

            return autoIncrementFields[0];
        }

        /// <summary>
        /// Validates the convention that an AutoIncrement field, if a primary key is declared,
        /// is the single-column primary key. Mirrors the constraint enforced by the MySQL and
        /// SQLite builders so AutoIncrement schemas behave consistently across providers.
        /// </summary>
        private void ValidateAutoIncrement()
        {
            var autoIncrementField = GetAutoIncrementField();
            if (autoIncrementField == null) return;

            var primaryKey = this.TableSchema.GetPrimaryKey();
            if (primaryKey == null) return;

            if (primaryKey.IndexFields!.Count != 1
                || !StrFunc.IsEquals(primaryKey.IndexFields[0].FieldName, autoIncrementField.FieldName))
            {
                throw new InvalidOperationException(
                    $"On Oracle, AutoIncrement field '{autoIncrementField.FieldName}' must be the single-column primary key. "
                    + "Either restructure the schema or use FieldDbType.Long instead.");
            }
        }

        /// <summary>
        /// Gets the CREATE TABLE statement plus trailing COMMENT and CREATE INDEX statements.
        /// </summary>
        private string GetCreateTableCommandText()
        {
            string tableName = this.TableSchema.TableName;
            var autoIncrementField = GetAutoIncrementField();
            string fields = GetFieldsCommandText(autoIncrementField);
            string primaryKey = GetPrimaryKeyCommandText(tableName, autoIncrementField);
            string tableComment = GetTableCommentStatement(tableName);
            string columnComments = GetColumnCommentStatements(tableName);
            string indexes = GetIndexesCommandText(tableName);

            var sb = new StringBuilder();
            sb.Append(CultureInfo.InvariantCulture, $"CREATE TABLE {OracleSchemaHelper.QuoteName(tableName)} (\r\n{fields}");
            if (StrFunc.IsNotEmpty(primaryKey))
                sb.Append(CultureInfo.InvariantCulture, $",\r\n  {primaryKey}");
            sb.Append("\r\n);");
            if (StrFunc.IsNotEmpty(tableComment))
                sb.Append(CultureInfo.InvariantCulture, $"\r\n{tableComment};");
            if (StrFunc.IsNotEmpty(columnComments))
                sb.Append(CultureInfo.InvariantCulture, $"\r\n{columnComments}");
            if (StrFunc.IsNotEmpty(indexes))
                sb.Append(CultureInfo.InvariantCulture, $"\r\n{indexes}");
            return sb.ToString();
        }

        /// <summary>
        /// Gets the SQL fragment for all column definitions. The AutoIncrement column is
        /// emitted with the Oracle <c>GENERATED BY DEFAULT AS IDENTITY</c> form via
        /// <see cref="OracleSchemaHelper.GetAutoIncrementColumnDefinition"/>.
        /// </summary>
        private string GetFieldsCommandText(DbField? autoIncrementField)
        {
            var sb = new StringBuilder();
            foreach (DbField field in this.TableSchema.Fields!)
            {
                if (sb.Length > 0)
                    sb.Append(",\r\n");
                if (autoIncrementField != null && field == autoIncrementField)
                    sb.Append("  " + OracleSchemaHelper.GetAutoIncrementColumnDefinition(field));
                else
                    sb.Append("  " + OracleSchemaHelper.GetColumnDefinition(field));
            }
            return sb.ToString();
        }

        /// <summary>
        /// Gets the table-level PRIMARY KEY constraint SQL fragment. Oracle does not allow
        /// inline column-level PK, so the constraint is emitted in-line with the CREATE TABLE
        /// for both AutoIncrement and non-AutoIncrement schemas.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        /// <param name="autoIncrementField">The AutoIncrement field, if any.</param>
        private string GetPrimaryKeyCommandText(string tableName, DbField? autoIncrementField)
        {
            var index = this.TableSchema.GetPrimaryKey();
            // When the schema has no declared PK but defines an AutoIncrement field, treat
            // that column as the implicit single-column PK (consistent with MySQL/SQLite).
            if (index == null && autoIncrementField == null) return string.Empty;

            string[] pkFieldNames;
            string pkConstraintNamePattern;
            if (index != null)
            {
                pkFieldNames = index.IndexFields!.Select(f => f.FieldName).ToArray();
                pkConstraintNamePattern = index.Name;
            }
            else
            {
                pkFieldNames = new[] { autoIncrementField!.FieldName };
                pkConstraintNamePattern = "pk_{0}";
            }

            var fieldBuilder = new StringBuilder();
            foreach (var fieldName in pkFieldNames)
            {
                if (fieldBuilder.Length > 0)
                    fieldBuilder.Append(", ");
                fieldBuilder.Append(OracleSchemaHelper.QuoteName(fieldName));
            }

            string name = StrFunc.Format(pkConstraintNamePattern, tableName);
            return $"CONSTRAINT {OracleSchemaHelper.QuoteName(name)} PRIMARY KEY ({fieldBuilder})";
        }

        /// <summary>
        /// Gets the <c>COMMENT ON TABLE</c> statement when the schema has a non-empty
        /// <see cref="TableSchema.DisplayName"/>; otherwise empty. The schema reader
        /// round-trips the table caption from <c>ALL_TAB_COMMENTS</c>, so emitting this here
        /// keeps fixture re-runs idempotent.
        /// </summary>
        private string GetTableCommentStatement(string tableName)
        {
            if (StrFunc.IsEmpty(TableSchema.DisplayName))
                return string.Empty;

            return $"COMMENT ON TABLE {OracleSchemaHelper.QuoteName(tableName)} IS '{OracleSchemaHelper.EscapeSqlString(TableSchema.DisplayName)}'";
        }

        /// <summary>
        /// Gets the <c>COMMENT ON COLUMN</c> statements for every field with a non-empty
        /// caption, separated by line breaks.
        /// </summary>
        private string GetColumnCommentStatements(string tableName)
        {
            var sb = new StringBuilder();
            foreach (DbField field in this.TableSchema.Fields!)
            {
                string commentStmt = OracleSchemaHelper.GetCommentStatement(tableName, field);
                if (StrFunc.IsEmpty(commentStmt)) continue;
                sb.Append(commentStmt);
                sb.Append(";\r\n");
            }
            return sb.ToString().TrimEnd();
        }

        /// <summary>
        /// Gets the SQL statements for creating all non-primary-key indexes.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        private string GetIndexesCommandText(string tableName)
        {
            var sb = new StringBuilder();
            foreach (TableSchemaIndex index in this.TableSchema.Indexes!.Where(i => !i.PrimaryKey))
            {
                sb.AppendLine(GetIndexCommandText(tableName, index));
            }
            return sb.ToString().Trim();
        }

        /// <summary>
        /// Gets the SQL statement for creating a single index.
        /// </summary>
        /// <param name="tableName">The table name.</param>
        /// <param name="index">The table schema index definition.</param>
        private static string GetIndexCommandText(string tableName, TableSchemaIndex index)
        {
            string name = StrFunc.Format(index.Name, tableName);
            var fieldBuilder = new StringBuilder();
            foreach (IndexField field in index.IndexFields!)
            {
                if (fieldBuilder.Length > 0)
                    fieldBuilder.Append(", ");
                fieldBuilder.Append(CultureInfo.InvariantCulture,
                    $"{OracleSchemaHelper.QuoteName(field.FieldName)} {field.SortDirection.ToString().ToUpperInvariant()}");
            }

            string uniqueClause = index.Unique ? "UNIQUE " : string.Empty;
            return $"CREATE {uniqueClause}INDEX {OracleSchemaHelper.QuoteName(name)} ON {OracleSchemaHelper.QuoteName(tableName)} ({fieldBuilder});";
        }
    }
}
