using Bee.Db.Ddl;
using Bee.Definition.Database;

namespace Bee.Db.Providers.Oracle
{
    /// <summary>
    /// Oracle 19c+ CREATE TABLE builder. Counterpart to
    /// <see cref="MySql.MySqlCreateTableCommandBuilder"/> and
    /// <see cref="PostgreSql.PgCreateTableCommandBuilder"/>.
    /// </summary>
    /// <remarks>
    /// Skeleton; the full implementation lands in a follow-up commit. Dialect decisions
    /// (<c>VARCHAR2(n CHAR)</c> with <c>NLS_LENGTH_SEMANTICS=CHAR</c> semantics,
    /// <c>NUMBER(p,s)</c> as the universal numeric, <c>GENERATED BY DEFAULT AS IDENTITY</c>
    /// for auto-increment, <c>TIMESTAMP(6)</c>, <c>RAW(16)</c> for GUIDs, separate
    /// <c>COMMENT ON COLUMN</c> statements) are documented in
    /// docs/plans/plan-oracle-support.md.
    /// </remarks>
    public class OracleCreateTableCommandBuilder : ICreateTableCommandBuilder
    {
        private const string NotImplementedMessage =
            "Oracle CREATE TABLE builder is not yet implemented. See docs/plans/plan-oracle-support.md.";

        /// <inheritdoc />
        public string GetCommandText(TableSchema tableSchema) => throw new NotImplementedException(NotImplementedMessage);
    }
}
