using Bee.Base;

namespace Bee.Definition.Identity
{
    /// <summary>
    /// Backend session info that records runtime data for the connection established between a user and the server.
    /// </summary>
    public class SessionInfo : IKeyObject, IUserInfo
    {
        #region IKeyObject Interface

        /// <summary>
        /// Gets the item key value.
        /// </summary>
        public string GetKey()
        {
            return this.AccessToken.ToString();
        }

        #endregion

        /// <summary>
        /// Gets or sets the access token.
        /// </summary>
        public Guid AccessToken { get; set; } = Guid.Empty;

        /// <summary>
        /// Gets or sets the expiration time (UTC) of the access token after a successful login.
        /// </summary>
        public DateTime ExpiredAt { get; set; }

        /// <summary>
        /// Gets or sets the user account ID.
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the user name.
        /// </summary>
        public string UserName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the user culture (e.g., zh-TW, en-US).
        /// </summary>
        public string Culture { get; set; } = "zh-TW";

        /// <summary>
        /// Gets or sets the user time zone (IANA format recommended, e.g., Asia/Taipei).
        /// </summary>
        public string TimeZone { get; set; } = "Asia/Taipei";

        /// <summary>
        /// Gets or sets the API encryption key used for bidirectional data encryption between the client and server.
        /// This key is dynamically generated by the server and returned to the client at login.
        /// </summary>
        public byte[] ApiEncryptionKey { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// Returns a string representation of this object.
        /// </summary>
        public override string ToString()
        {
            return $"{UserId} : {UserName}";
        }
    }
}
