using Bee.Base;

namespace Bee.Definition.Identity
{
    /// <summary>
    /// Backend session info that records runtime data for the connection established between a user and the server.
    /// </summary>
    public class SessionInfo : IKeyObject, IUserInfo
    {
        #region IKeyObject Interface

        /// <summary>
        /// Gets the item key value.
        /// </summary>
        public string GetKey()
        {
            return this.AccessToken.ToString();
        }

        #endregion

        /// <summary>
        /// Gets or sets the access token.
        /// </summary>
        public Guid AccessToken { get; set; } = Guid.Empty;

        /// <summary>
        /// Gets or sets the expiration time (UTC) of the access token after a successful login.
        /// </summary>
        public DateTime ExpiredAt { get; set; }

        /// <summary>
        /// Gets or sets the user account ID.
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the user name.
        /// </summary>
        public string UserName { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the ID of the company the user has entered for this session.
        /// </summary>
        /// <remarks>
        /// <c>null</c> means the user has logged in but has not yet entered a company.
        /// Business operations that depend on a company context (FormBO, ReportBO, etc.)
        /// must reject requests with a <c>null</c> value via <c>CompanyNotEntered</c>.
        /// The value is set by <c>EnterCompany</c> and cleared by <c>LeaveCompany</c> /
        /// <c>Logout</c>.
        /// </remarks>
        public string? CompanyId { get; set; }

        /// <summary>
        /// Gets or sets the tenant customization code currently in effect for this session.
        /// </summary>
        /// <remarks>
        /// Empty means the standard (non-customized) deployment — every customization overlay
        /// short-circuits to the base layer. The value is derived from
        /// <c>CompanyInfo.CustomizeId</c> by <c>EnterCompany</c> and cleared by
        /// <c>LeaveCompany</c> / <c>Logout</c> (in step with <see cref="CompanyId"/>).
        /// </remarks>
        public string CustomizeId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the user culture (e.g., zh-TW, en-US).
        /// </summary>
        public string Culture { get; set; } = "zh-TW";

        /// <summary>
        /// Gets or sets the user time zone (IANA format recommended, e.g., Asia/Taipei).
        /// </summary>
        public string TimeZone { get; set; } = "Asia/Taipei";

        /// <summary>
        /// Gets or sets the API encryption key used for bidirectional data encryption between the client and server.
        /// This key is dynamically generated by the server and returned to the client at login.
        /// </summary>
        public byte[] ApiEncryptionKey { get; set; } = Array.Empty<byte>();

        /// <summary>
        /// Gets or sets the role ids assigned to the user within the current company.
        /// </summary>
        /// <remarks>
        /// Populated by <c>EnterCompany</c> after the user enters a company (each id is an
        /// <c>st_role.sys_id</c>); the layer-1 permission check OR-merges these roles' grants.
        /// Cleared by <c>LeaveCompany</c> / <c>Logout</c> in step with <see cref="CompanyId"/>.
        /// </remarks>
        public ICollection<string> Roles { get; set; } = [];

        /// <summary>
        /// Gets or sets the current user's row id (<c>st_user.sys_rowid</c>) within the entered company.
        /// </summary>
        /// <remarks>
        /// Resolved and snapshotted by <c>EnterCompany</c> for record-scope <c>Own</c> filtering;
        /// <see cref="System.Guid.Empty"/> until a company is entered. Cleared by
        /// <c>LeaveCompany</c> / <c>Logout</c> in step with <see cref="CompanyId"/>.
        /// </remarks>
        public Guid UserRowId { get; set; } = Guid.Empty;

        /// <summary>
        /// Gets or sets the current user's linked employee row id (<c>st_employee.sys_rowid</c>) in
        /// the entered company.
        /// </summary>
        /// <remarks>
        /// Resolved and snapshotted by <c>EnterCompany</c> for record-scope <c>Own</c> filtering;
        /// <see cref="System.Guid.Empty"/> when the user has no employee in this company (or no
        /// company entered). Cleared by <c>LeaveCompany</c> / <c>Logout</c>.
        /// </remarks>
        public Guid EmployeeRowId { get; set; } = Guid.Empty;

        /// <summary>
        /// Gets or sets the current user's department row id (<c>st_employee.dept_rowid</c>) in the
        /// entered company.
        /// </summary>
        /// <remarks>
        /// Resolved and snapshotted by <c>EnterCompany</c> for record-scope <c>Dept</c> /
        /// <c>DeptAndSub</c> filtering; <see cref="System.Guid.Empty"/> when the user has no employee
        /// or no department (or no company entered). Cleared by <c>LeaveCompany</c> / <c>Logout</c>.
        /// </remarks>
        public Guid DeptRowId { get; set; } = Guid.Empty;

        /// <summary>
        /// Returns a string representation of this object.
        /// </summary>
        public override string ToString()
        {
            return $"{UserId} : {UserName}";
        }
    }
}
